"""
Django settings for ragtime project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#un!w=ibtio9)apch6*sd(k3i445ptoi6*=nv2vhdv!v+ty9ay'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    'core',
    'episodes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ragtime.urls'

TEST_RUNNER = 'ragtime.test_runner.PostgresTestRunner'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ragtime.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('RAGTIME_DB_NAME', 'ragtime'),
        'USER': os.getenv('RAGTIME_DB_USER', 'ragtime'),
        'PASSWORD': os.getenv('RAGTIME_DB_PASSWORD', 'ragtime'),
        'HOST': os.getenv('RAGTIME_DB_HOST', 'localhost'),
        'PORT': os.getenv('RAGTIME_DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded/downloaded content)
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Q2 — async task queue with ORM broker
Q_CLUSTER = {
    'name': 'ragtime',
    'workers': 2,
    'timeout': 900,
    'retry': 1200,
    'orm': 'default',
    'save_limit': 250,
    'ack_failures': True,
    'max_attempts': 1,
    'catch_up': False,
}

# RAGtime provider configuration
RAGTIME_SCRAPING_PROVIDER = os.getenv('RAGTIME_SCRAPING_PROVIDER', 'openai')
RAGTIME_SCRAPING_API_KEY = os.getenv('RAGTIME_SCRAPING_API_KEY', '')
RAGTIME_SCRAPING_MODEL = os.getenv('RAGTIME_SCRAPING_MODEL', 'gpt-4.1-mini')

# Audio processing
RAGTIME_MAX_AUDIO_SIZE = 25 * 1024 * 1024  # 25MB — Whisper API limit

# Transcription
RAGTIME_TRANSCRIPTION_PROVIDER = os.getenv('RAGTIME_TRANSCRIPTION_PROVIDER', 'openai')
RAGTIME_TRANSCRIPTION_API_KEY = os.getenv('RAGTIME_TRANSCRIPTION_API_KEY', '')
RAGTIME_TRANSCRIPTION_MODEL = os.getenv('RAGTIME_TRANSCRIPTION_MODEL', 'whisper-1')

# Summarization
RAGTIME_SUMMARIZATION_PROVIDER = os.getenv('RAGTIME_SUMMARIZATION_PROVIDER', 'openai')
RAGTIME_SUMMARIZATION_API_KEY = os.getenv('RAGTIME_SUMMARIZATION_API_KEY', '')
RAGTIME_SUMMARIZATION_MODEL = os.getenv('RAGTIME_SUMMARIZATION_MODEL', 'gpt-4.1-mini')

# Entity extraction
RAGTIME_EXTRACTION_PROVIDER = os.getenv('RAGTIME_EXTRACTION_PROVIDER', 'openai')
RAGTIME_EXTRACTION_API_KEY = os.getenv('RAGTIME_EXTRACTION_API_KEY', '')
RAGTIME_EXTRACTION_MODEL = os.getenv('RAGTIME_EXTRACTION_MODEL', 'gpt-4.1-mini')

# Entity resolution
RAGTIME_RESOLUTION_PROVIDER = os.getenv('RAGTIME_RESOLUTION_PROVIDER', 'openai')
RAGTIME_RESOLUTION_API_KEY = os.getenv('RAGTIME_RESOLUTION_API_KEY', '')
RAGTIME_RESOLUTION_MODEL = os.getenv('RAGTIME_RESOLUTION_MODEL', 'gpt-4.1-mini')

# Translation (used by recovery agent)
RAGTIME_TRANSLATION_PROVIDER = os.getenv('RAGTIME_TRANSLATION_PROVIDER', 'openai')
RAGTIME_TRANSLATION_API_KEY = os.getenv('RAGTIME_TRANSLATION_API_KEY', '')
RAGTIME_TRANSLATION_MODEL = os.getenv('RAGTIME_TRANSLATION_MODEL', 'gpt-4.1-mini')

# Wikidata integration
RAGTIME_WIKIDATA_USER_AGENT = os.getenv(
    'RAGTIME_WIKIDATA_USER_AGENT',
    'RAGtime/0.1 (https://github.com/rafacm/ragtime)',
)
RAGTIME_WIKIDATA_CACHE_TTL = int(os.getenv('RAGTIME_WIKIDATA_CACHE_TTL', '604800'))
RAGTIME_WIKIDATA_DEBOUNCE_MS = int(os.getenv('RAGTIME_WIKIDATA_DEBOUNCE_MS', '300'))
RAGTIME_WIKIDATA_MIN_CHARS = int(os.getenv('RAGTIME_WIKIDATA_MIN_CHARS', '3'))

# Caches
_wikidata_cache_backend = os.getenv('RAGTIME_WIKIDATA_CACHE_BACKEND', 'filebased')
if _wikidata_cache_backend == 'db':
    _wikidata_cache = {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'wikidata_cache',
        'TIMEOUT': RAGTIME_WIKIDATA_CACHE_TTL,
    }
else:
    if _wikidata_cache_backend != 'filebased':
        import logging as _logging
        _logging.getLogger(__name__).warning(
            "Unknown RAGTIME_WIKIDATA_CACHE_BACKEND '%s', using 'filebased'",
            _wikidata_cache_backend,
        )
    _wikidata_cache = {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': str(BASE_DIR / '.cache' / 'wikidata'),
        'TIMEOUT': RAGTIME_WIKIDATA_CACHE_TTL,
        'OPTIONS': {
            'MAX_ENTRIES': 5000,
        },
    }

# Telemetry (OpenTelemetry)
RAGTIME_OTEL_COLLECTORS = os.getenv('RAGTIME_OTEL_COLLECTORS', '')
RAGTIME_OTEL_SERVICE_NAME = os.getenv('RAGTIME_OTEL_SERVICE_NAME', 'ragtime')
RAGTIME_OTEL_JAEGER_ENDPOINT = os.getenv('RAGTIME_OTEL_JAEGER_ENDPOINT', 'http://localhost:4318')

# Langfuse collector settings (used when 'langfuse' is in RAGTIME_OTEL_COLLECTORS)
RAGTIME_LANGFUSE_SECRET_KEY = os.getenv('RAGTIME_LANGFUSE_SECRET_KEY', '')
RAGTIME_LANGFUSE_PUBLIC_KEY = os.getenv('RAGTIME_LANGFUSE_PUBLIC_KEY', '')
RAGTIME_LANGFUSE_HOST = os.getenv('RAGTIME_LANGFUSE_HOST', 'http://localhost:3000')

# Recovery layer
RAGTIME_RECOVERY_CHAIN = ["agent", "human"]
RAGTIME_RECOVERY_AGENT_ENABLED = os.getenv('RAGTIME_RECOVERY_AGENT_ENABLED', 'false').lower() in ('true', '1', 'yes')
RAGTIME_RECOVERY_AGENT_API_KEY = os.getenv('RAGTIME_RECOVERY_AGENT_API_KEY', '')
RAGTIME_RECOVERY_AGENT_MODEL = os.getenv('RAGTIME_RECOVERY_AGENT_MODEL', 'openai:gpt-4.1-mini')
RAGTIME_RECOVERY_AGENT_TIMEOUT = int(os.getenv('RAGTIME_RECOVERY_AGENT_TIMEOUT', '120'))

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'wikidata': _wikidata_cache,
}
