# Generated by Django 5.2.12 on 2026-03-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='episode',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='episode',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='scraped_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('needs_review', 'Needs Review'), ('downloading', 'Downloading'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('extracting', 'Extracting'), ('deduplicating', 'Deduplicating'), ('embedding', 'Embedding'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
