# Generated by Django 5.2.12 on 2026-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_episode_audio_url_episode_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='episodes/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('needs_review', 'Needs Review'), ('downloading', 'Downloading'), ('resizing', 'Resizing'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('extracting', 'Extracting'), ('deduplicating', 'Deduplicating'), ('embedding', 'Embedding'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
