# Generated by Django 5.2.12 on 2026-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_episode_audio_file_episode_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='transcript_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
