# Generated by Django 5.2.12 on 2026-03-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0004_episode_transcript_episode_transcript_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='summary_generated',
            field=models.TextField(blank=True, default=''),
        ),
    ]
