# Generated by Django 5.2.12 on 2026-03-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0005_episode_summary_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='entities_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
