# Generated by Django 5.2.12 on 2026-03-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0006_episode_entities_json'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE episodes_episode SET status='resolving' WHERE status='deduplicating'",
            reverse_sql="UPDATE episodes_episode SET status='deduplicating' WHERE status='resolving'",
        ),
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('needs_review', 'Needs Review'), ('downloading', 'Downloading'), ('resizing', 'Resizing'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('extracting', 'Extracting'), ('resolving', 'Resolving'), ('embedding', 'Embedding'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'name'), name='unique_entity_type_name')],
            },
        ),
        migrations.CreateModel(
            name='EntityMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='episodes.entity')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mentions', to='episodes.episode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity', 'episode', 'context'), name='unique_entity_episode_context')],
            },
        ),
    ]
