# Generated by Django 5.2.12 on 2026-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0011_finalize_entity_type_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitytype',
            name='description',
            field=models.TextField(help_text='What this entity type represents, e.g. A specific date/time/place of a recording.'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='examples',
            field=models.JSONField(default=list, help_text='Example entities of this type, e.g. The Blackhawk Sessions, 1959 Sessions'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='key',
            field=models.CharField(help_text='Unique snake_case identifier, e.g. recording_session', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='name',
            field=models.CharField(help_text='Human-readable label, e.g. Recording Session', max_length=100),
        ),
    ]
