# Generated by Django 5.2.12 on 2026-03-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0012_alter_entitytype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
