# Generated by Django 5.2.12 on 2026-03-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0013_episode_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('needs_review', 'Needs Review'), ('downloading', 'Downloading'), ('resizing', 'Resizing'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('chunking', 'Chunking'), ('extracting', 'Extracting'), ('resolving', 'Resolving'), ('embedding', 'Embedding'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('segment_start', models.PositiveIntegerField()),
                ('segment_end', models.PositiveIntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='episodes.episode')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('episode', 'index'), name='unique_episode_chunk_index')],
            },
        ),
    ]
