# Generated by Django 5.2.12 on 2026-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0016_chunk_level_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Wikidata entity Q-ID, e.g. Q93341 for 'Miles Davis'", max_length=20),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='wikidata_id',
            field=models.CharField(blank=True, default='', help_text="Wikidata class Q-ID, e.g. Q639669 for 'musician'", max_length=20),
        ),
    ]
