# Generated by Django 5.2.12 on 2026-03-18 14:08

import django.db.models.deletion
from django.db import migrations, models


def migrate_needs_review_to_failed(apps, schema_editor):
    """Convert any existing needs_review episodes to failed."""
    Episode = apps.get_model('episodes', 'Episode')
    Episode.objects.filter(status='needs_review').update(
        status='failed',
        error_message='Migrated from needs_review: incomplete metadata',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0017_entity_wikidata_id_entitytype_wikidata_id'),
    ]

    operations = [
        migrations.RunPython(
            migrate_needs_review_to_failed,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('downloading', 'Downloading'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('chunking', 'Chunking'), ('extracting', 'Extracting'), ('resolving', 'Resolving'), ('embedding', 'Embedding'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('step_name', models.CharField(max_length=20)),
                ('error_type', models.CharField(blank=True, default='', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('exception_class', models.CharField(blank=True, default='', max_length=200)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_events', to='episodes.episode')),
                ('processing_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='episodes.processingstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('attempted', 'Attempted'), ('awaiting_human', 'Awaiting Human'), ('resolved', 'Resolved')], default='attempted', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=50)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_attempts', to='episodes.episode')),
                ('pipeline_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_attempts', to='episodes.pipelineevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
