# Generated by Django 5.2.12 on 2026-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0018_alter_episode_status_pipelineevent_recoveryattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymention',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
