# Generated by Django 5.2.12 on 2026-03-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0019_entitymention_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='linking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('linked', 'Linked'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10),
        ),
    ]
