# Generated by Django 5.2.12 on 2026-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0019_entitymention_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='musicbrainz_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='MusicBrainz entity gid (UUID).', max_length=36),
        ),
        migrations.AddField(
            model_name='entity',
            name='wikidata_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='wikidata_last_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='wikidata_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('not_found', 'Not Found'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='musicbrainz_filter',
            field=models.JSONField(blank=True, default=dict, help_text='Extra filter applied to MB candidates, e.g. {"artist_type": "Person"} or {"area_type": "City"}.'),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='musicbrainz_table',
            field=models.CharField(blank=True, default='', help_text='MusicBrainz table to query for candidates (artist, release_group, label, place, work, area). Empty = no MB lookup.', max_length=64),
        ),
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('scraping', 'Scraping'), ('downloading', 'Downloading'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('chunking', 'Chunking'), ('extracting', 'Extracting'), ('resolving', 'Resolving'), ('embedding', 'Embedding'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='processingrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('episode',), name='unique_running_run_per_episode'),
        ),
    ]
