# Generated by Django 5.2.12 on 2026-03-31 06:36

from django.db import migrations


def set_linked_for_existing(apps, schema_editor):
    Entity = apps.get_model("episodes", "Entity")
    Entity.objects.exclude(wikidata_id="").update(linking_status="linked")


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0020_add_entity_linking_status'),
    ]

    operations = [
        migrations.RunPython(set_linked_for_existing, reverse_noop),
    ]
