# Generated by Django 5.2.12 on 2026-03-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0021_set_linking_status_for_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='linking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('linking', 'Linking'), ('linked', 'Linked'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10),
        ),
    ]
