# Generated by Django 5.2.12 on 2026-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0021_rename_scraping_to_fetching_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='guid',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
