# Generated by Django 5.2.12 on 2026-04-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0022_add_episode_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoveryattempt',
            name='pipeline_event',
        ),
        migrations.RemoveField(
            model_name='processingrun',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='processingstep',
            name='run',
        ),
        migrations.RemoveField(
            model_name='recoveryattempt',
            name='episode',
        ),
        migrations.DeleteModel(
            name='PipelineEvent',
        ),
        migrations.DeleteModel(
            name='ProcessingRun',
        ),
        migrations.DeleteModel(
            name='ProcessingStep',
        ),
        migrations.DeleteModel(
            name='RecoveryAttempt',
        ),
    ]
