# Generated by Django 5.2.12 on 2026-04-29 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0023_drop_processing_pipeline_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='scraped_html',
        ),
        migrations.AddField(
            model_name='episode',
            name='aggregator_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='episode',
            name='audio_format',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='episode',
            name='canonical_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='episode',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='episode',
            name='source_kind',
            field=models.CharField(blank=True, choices=[('canonical', 'Canonical'), ('aggregator', 'Aggregator'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.CreateModel(
            name='FetchDetailsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_index', models.PositiveIntegerField(help_text='1, 2, 3… per episode — increments on re-run.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(default='', help_text='Pydantic AI model string at run time (e.g. openai:gpt-4.1-mini).', max_length=100)),
                ('outcome', models.CharField(blank=True, choices=[('ok', 'Ok'), ('partial', 'Partial'), ('not_a_podcast_episode', 'Not A Podcast Episode'), ('unreachable', 'Unreachable'), ('extraction_failed', 'Extraction Failed')], default='', max_length=30)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('tool_calls_json', models.JSONField(blank=True, default=list)),
                ('usage_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('dbos_workflow_id', models.CharField(blank=True, db_index=True, default='', help_text='DBOS.workflow_id at orchestrator entry — cross-reference for forensics.', max_length=200)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_details_runs', to='episodes.episode')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['episode', '-run_index'], name='episodes_fe_episode_bf55ed_idx'), models.Index(fields=['outcome'], name='episodes_fe_outcome_6d53ce_idx'), models.Index(fields=['-started_at'], name='episodes_fe_started_405579_idx')],
                'unique_together': {('episode', 'run_index')},
            },
        ),
    ]
