# Generated by Django 5.2.12 on 2026-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0024_fetch_details_cross_linking'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='show_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
